package com.yoogesh.rules

import com.yoogesh.visa.validation.Validation;
import com.yoogesh.visa.model.VisaApplication;
import com.yoogesh.visa.model.Visa;

import java.time.LocalDate

rule "Issue visa for valid applications"
	dialect "mvel"
	when
	  $visaApplication: VisaApplication( this.validation == Validation.PASSED )
	then
	  Visa visa = new Visa( $visaApplication.getPassportNumber() );
	  System.out.println("Issue " + visa);
	  insertLogical( visa )
end